sensor:
  - platform: uptime
    name: ESP32_Uptime
    id: uptime
    update_interval: 30s

text_sensor:
  - platform: template
    name: "Uptime "
    lambda: |-
      uint32_t dur = id(uptime).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      int len = snprintf(buffer, sizeof(buffer), "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      if (len < 0 || len >= sizeof(buffer)) {
        return {};
      }
      return {buffer};
    icon: mdi:clock-start
    update_interval: 30s
